### ISSUE TITLE
The demo doesn’t seem to work anymore

### ISSUE THREAD

**Issue by danmysak** [dimitrinicolas/overflow-color#1]
MacOS Catalina, in both Chrome 79 and Safari:

![image](https://user-images.githubusercontent.com/6333637/72648749-8a7aee80-3984-11ea-9338-aff48f9009f9.png)

**Comment by gerasimvol** [comment]
it is working when you have enough scroll

**Comment by dimitrinicolas** [comment]
@danmysak I'm really sorry, I hadn't seen this issue before.

Like @gerasimvol I think that you tried it with a window's height greater than the document content height.

Unfortunately, we can't assign the header red color to the `html` `background-color` in this case without it appearing under the blue footer. I made the choice to disable the top color and always set the bottom one for this situation.

Thank you for this report, I need to update the readme.

If this was not your case, please make sure to reopen this issue. 😄
